// Generated by CoffeeScript 1.6.2
(function() {
  var faithful, memoblock;

  faithful = require("faithful");

  module.exports = memoblock = {
    "do": function(functions) {
      return this.doWith({}, functions);
    },
    doWith: function(memo, functions) {
      var doStep;

      doStep = function(fn) {
        var r;

        r = fn.call(memo, memo);
        if (r && typeof r.then === "function") {
          return r.then(function() {
            return faithful.collect(memo);
          });
        } else {
          return faithful.collect(memo);
        }
      };
      return faithful.eachSeries(functions, doStep, {
        handleResult: function(result) {
          return memo = result;
        },
        getFinalValue: function() {
          return memo;
        }
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=memoblock.map
*/
